# Default values for stash-postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# we are declaring these values as global so that parent chart can overwrite them
docker:
  registry: stashed
  image: stash-postgres
  tag: 10.6

# optional argument to send pgdump or psql command
backup:
  pgArgs: ""
restore:
  pgArgs: ""
